### ISSUE TITLE
API data from Investing.com

### ISSUE THREAD

**Issue by shumakerro** [arbuzovv/rusquant#11]
Thanks for authoring the rusquant package.
I get this message:
Error in getInvesting_id(Symbol) : object 'json_data' not found
What am I doing wrong?

**Comment by Korvalyov** [comment]
Got a similar issue with getSymbols when source is investing.com
function started returning the following error:
""cannot connect to server""
Issue started to happen just this week.

**Comment by Korvalyov** [comment]
Follow up to this issue:

debugging function getSymbols.Investing

after request r is created using POST in the following line:

r <- POST(url,headers,body = data,encode = "raw")
then on the next line, we have
status_code(r) as conditional for data output called Records

after testing under different symbol requests, always got error 403 (forbidden)

could be that Investing got smart and barred against this kind of scraping :(

**Comment by arbuzovv** [comment]
getInvesting was deprecated due ohlc data policy of investing.com
