### ISSUE TITLE
getDividends() throws error 

### ISSUE THREAD

**Issue by dkibalnikov** [arbuzovv/rusquant#15]
simple request `getDividends()` throws error :
```
unique(Records_result) : object 'Records_result' not found
```
digging deeper to issue I found out investing.com returns 403 status for any request. It seems like issue related to  [case](https://github.com/alvarobartt/investpy/issues/600)

Eventually, seems like investing.com technically prohibits getting data programmatically :(

**Comment by arbuzovv** [comment]
Not regular issues, I think problem was in side of Investing. Currently all is working
