### ISSUE TITLE
Error message from getSymbols.MarketWatch

### ISSUE THREAD

**Issue by rabarros01** [arbuzovv/rusquant#17]
Hello,

I have been trying to use the function "getSymbols.MarketWatch" to retrieve data on CBOE VIX Futures contracts (symbols: "VX.1", "VXF24"), but I get the following error message after inserting the command below:

getSymbols.MarketWatch("VXF24", env = globalenv(), from = "2020-01-01", to = "2023-12-27")

Downloaded 99085 bytes...Error in curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) : HTTP error 404.

Any idea of why this is happening and how to deal with it so that the data can be obtained?

Many thanks,
rabarros01

**Comment by arbuzovv** [comment]
Try new version >= 1.1.0. and command
getSymbols.MarketWatch("VXF25",market = 'future',from = "2023-12-01", to = "2024-05-27")
