### ISSUE TITLE
Finam moved to https from http

### ISSUE THREAD

**Issue by gBopHuk** [arbuzovv/rusquant#3]
<pre>
getSymbols("SPFB.BR",src="Finam",from=Sys.Date()-7,to=Sys.Date(),period="day")
    As of 0.4-0, ‘getSymbols’ uses env=parent.frame() and
 auto.assign=TRUE by default.

 This  behavior  will be  phased out in 0.5-0  when the call  will
 default to use auto.assign=FALSE. getOption("getSymbols.env") and 
 getOptions("getSymbols.auto.assign") are now checked for alternate defaults

 This message is shown once per session and may be disabled by setting 
 options("getSymbols.warning4.0"=FALSE). See ?getSymbols for more details.
Error in download.file(stocklist.URL, destfile = tmp, quiet = !verbose) : 
  cannot open URL 'http://www.finam.ru/cache/icharts/icharts.js'
</pre>

URL 'http://www.finam.ru/cache/icharts/icharts.js' redirects to the 'httpS://www.finam.ru/cache/icharts/icharts.js' in the browsers

**Comment by gBopHuk** [comment]
Commit 83dc7b9127698d642057e65279cb5b3c012605a5 fix this problem. Thanks!

**Comment by gBopHuk** [comment]
83dc7b9 doesn't works in windows but works in linux
<pre>
 > getSymbols("SPFB.BR",src="Finam",from=Sys.Date()-7,to=Sys.Date())
Ошибка в download.file(stocklist.URL, destfile = tmp, quiet = !verbose) :
  не могу открыть URL 'https://www.finam.ru/cache/icharts/icharts.js'
Вдобавок: Предупреждение:
В download.file(stocklist.URL, destfile = tmp, quiet = !verbose) :
  'InternetOpenUrl' не удалось: 'Сброшено подключение к этому серверу.'
</pre>

**Comment by arbuzovv** [comment]
Change method to curl_download
