### ISSUE TITLE
Полностью пропали котировки с финама

### ISSUE THREAD

**Issue by mikepumpkineater** [arbuzovv/rusquant#8]
![image](https://user-images.githubusercontent.com/63873988/79601365-ae9ab880-80b6-11ea-86ef-48080c469dc8.png)

Сегодня в середине дня полностью перестали загружаться данные с финама с ошибкой которая приложена на изображении. Утром работало на любых временных интервалах. Сейчас даже дневки не дает. Видел похожую проблему в вопросах , но сегодня не выходной. Не могу понять в чем сейчас проблема

**Comment by arbuzovv** [comment]
Ошибку увидел, действительно у меня она повторяется. Проблема, что финам что-то поменяло в своем API, сейчас при стандартном методе скачивания в файле вместо данных пишет "Автоматическая загрузка недоступна".  Ну и явно видно, если смотреть в инспекторе кода при загрузке много всего изменилось. Будем разбираться, не понятно на сколько хорошо они закрыли свой API или только изменили структуру. Пока в качестве альтернативы предлагаю попользовать в качестве источника mfd или алор (getSymbols('SBER',src='Mfd') и  getSymbols('SBER',src='Alor'))

**Comment by mikepumpkineater** [comment]
Спасибо за ответ, где можно смотреть актуальную информацию по работе пакета и трудностям которые возникают в процессе его эксплуатации?

**Comment by nikiie8** [comment]
Пока не работает загрузка с финама, не подскажите как можно загружать фьючерсы с алора или mdf?  Перепробывал разные написания тикеров - ничего не работает
